- name: Install openjdk
  apt:
    name: openjdk-11-jdk

- name: Create metabase User
  user:
    name: metabase
    shell: /usr/sbin/nologin
    home: /data/wwwroot/metabase
    create_home: no

- name: Create metabase directory
  file:
    path: /data/wwwroot/metabase
    state: directory
    owner: metabase
    group: metabase
    

- name: Download metabase
  get_url:
    dest: /data/wwwroot/metabase
    url: "{{metabase_download_url}}"
    owner: metabase
    group: metabase

- name: Set metabase config
  template:
    src: metabase.conf.jinja2
    dest: /data/wwwroot/metabase/metabase.conf
    owner: metabase
    group: metabase

- name: Setting metabase service
  copy:
    src: metabase.service
    dest: /lib/systemd/system/metabase.service

- name: Restart metabase
  service:
    name: metabase.service
    state: restarted
    enabled: yes

- name:  wait for metabase setup (about 5min)
  wait_for:
    port: 3000
    delay: 300
    timeout: 600
  

- name: set reverse porxy
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
