# install Metabase by OS_family
- debug:
    msg: Metabase will be installed on {{ ansible_distribution }} 

- include: "{{ansible_os_family}}.yml"

# configure Metabase

- name: Create metabase User
  user:
    name: metabase
    shell: /usr/sbin/nologin
    home: /data/wwwroot/metabase
    create_home: no

- name: Create metabase directory
  file:
    path: /data/wwwroot/metabase
    state: directory
    owner: metabase
    group: metabase
    
- name: Download metabase
  get_url:
    dest: /data/wwwroot/metabase
    url: "{{metabase_download_url}}"
    owner: metabase
    group: metabase

- name: Set metabase config
  template:
    src: metabase.conf.jinja2
    dest: /data/wwwroot/metabase/metabase.conf
    owner: metabase
    group: metabase

- name: Setting metabase service
  copy:
    src: metabase.service
    dest: /lib/systemd/system/metabase.service

- name: Restart metabase
  service:
    name: metabase.service
    state: restarted
    enabled: yes

- name:  wait for metabase setup (about 5min)
  wait_for:
    port: 3000
    delay: 300
    timeout: 600

# set soft link, -b over
# ln -sb src des

# display version and service state of components
- name: Get metabase version
  shell: sudo sh -c "echo 'no check version method for Metabase now' 1>> /data/logs/install_version.txt"

- name: Check metabase Service
  shell: systemctl status metabase | grep Active*
  register: check_metabase_service
  notify: check_metabase_service
